added "New On Otakugram" Card Slider
RektyRowdyy/Otakugram pull request #8
Opened 2024-06-26 07:29 UTC by RektyRowdyy

2024-06-30 11:56 UTC, 7373Mehar requested changes

2024-06-30 11:56 UTC, 7373Mehar commented on Otakugram-UI/frontend/src/components/Home/CardSlider/CardSlider.jsx
> +    if (arrowType === 'next') {
Make a constant file and fetch 'next' from that place.

2024-06-30 11:56 UTC, 7373Mehar commented on Otakugram-UI/frontend/src/components/Home/CardSlider/CardSlider.jsx
> +    else if (arrowType === 'prev') {
Make a constant file and fetch 'prev' from that place.

2024-06-30 11:56 UTC, 7373Mehar commented on Otakugram-UI/frontend/src/components/Home/CardSlider/CardSlider.jsx
> +        {
entire array from constant file.

2024-07-03 10:06 UTC, RektyRowdyy commented
@7373Mehar updated UI and transferred all the static data to constants.jsx

2024-07-03 18:27 UTC, 7373Mehar approved these changes

2024-10-05 16:41 UTC, merged